version: '3.6'

services:
  chatgpt:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env

  scrapper:
    build:
      context: ./scrapper/
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
